/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef ADMOBADS_AUTODEFS_H
#define ADMOBADS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADMOBADS_NAME "AdmobAds"
#define S3E_EXT_ADMOBADS_HASH 0x18b70240

#endif /* !ADMOBADS_AUTODEFS_H */
